name: LPMetaPlus
version: '1.1'
main: me.re4erka.lpmetaplus.LPMetaPlus
api-version: '1.19'
authors: [ RE4ERKA ]
description: Enhances the meta for LuckPerms.
website: t.me/re4erka
folia-supported: true
dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
